apiVersion: v2
name: corto-local-cluster
description: A Helm chart for deploying Corto services in a local cluster
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: slim
    version: "v0.6.0"
    repository: "oci://ghcr.io/agntcy/slim/helm"
  - name: nats
    version: "1.3.16"
    repository: "https://nats-io.github.io/k8s/helm/charts"
  - name: clickhouse
    version: "9.4.3"         
    repository: "oci://registry-1.docker.io/bitnamicharts"
  - name: opentelemetry-collector
    version: "0.138.0"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
  - name: grafana
    version: "10.1.2"
    repository: "oci://ghcr.io/grafana/helm-charts"
  - name: corto-exchange
    version: "0.0.7"
    repository: "file://../exchange"
  - name: corto-farm
    version: "0.0.5"
    repository: "file://../farm"
  - name: corto-ui
    version: "0.0.2"
    repository: "file://../corto-ui"

  