apiVersion: v2
name: lungo-local-cluster
description: A Helm chart for deploying Lungo services in a local cluster
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: slim
    version: "v0.6.0"
    repository: "oci://ghcr.io/agntcy/slim/helm"
  - name: nats
    version: "1.3.16"
    repository: "https://nats-io.github.io/k8s/helm/charts"
  - name: clickhouse
    version: "9.4.3"         
    repository: "oci://registry-1.docker.io/bitnamicharts"
  - name: opentelemetry-collector
    version: "0.138.0"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
  - name: grafana
    version: "10.1.2"
    repository: "oci://ghcr.io/grafana/helm-charts"
  - name: auction-supervisor
    version: "0.0.3"
    repository: "file://../auction-supervisor"
  - name: brazil-farm
    version: "0.0.6"
    repository: "file://../brazil-farm"
  - name: vietnam-farm
    version: "0.0.9"
    repository: "file://../vietnam-farm"
  - name: colombia-farm
    version: "0.0.11"
    repository: "file://../colombia-farm"
  - name: weather-mcp-server
    version: "0.0.4"
    repository: "file://../weather-mcp-server"
  - name: logistics-farm
    version: "0.0.1"
    repository: "file://../logistics-farm"
  - name: logistics-helpdesk
    version: "0.0.1"
    repository: "file://../logistics-helpdesk"
  - name: logistics-supervisor
    version: "0.0.3"
    repository: "file://../logistics-supervisor"
  - name: logistics-shipper
    version: "0.0.1"
    repository: "file://../logistics-shipper"
  - name: logistics-accountant
    version: "0.0.1"
    repository: "file://../logistics-accountant"
  - name: lungo-ui
    version: "0.0.5"
    repository: "file://../ui"

  