opentelemetry-collector:
  image:
    repository: otel/opentelemetry-collector-k8s
  mode: deployment

clickhouse:
  auth:
    username: "admin"
    password: "admin"
  keeper:
    enabled: false
  shards: 1
  replicaCount: 1
  image:
    repository: bitnamilegacy/clickhouse
    tag: 25.6.4-debian-12-r0
    pullPolicy: IfNotPresent

nats:
  readinessProbe:
    httpGet: { path: /healthz, port: 8222 }
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 6
  livenessProbe:
    httpGet: { path: /healthz, port: 8222 }
    initialDelaySeconds: 20
    periodSeconds: 20
    timeoutSeconds: 2
    failureThreshold: 6

weather-mcp-server:
  transportServerEndpoint: "nats://lungo-local-cluster-nats:4222"
  defaultMessageTransport: "NATS"
  otlpHttpEndpoint: "http://lungo-local-cluster-opentelemetry-collector:4318"

lungo-ui:
  environment: local
  config:
    exchangeAppApiUrl: "http://localhost:30080"
    logisticsAppApiUrl: "http://localhost:30081"
